import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<<< HEAD:book-bound/frontend/src/app/layout.tsx
========
import { AuthProvider } from "@/AuthProvider";
import Navbar from "./components/Navbar";
>>>>>>>> c7eec8b99a9c4069961b4ceb032059cb2a88b432:notera/src/app/layout.tsx

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<<< HEAD:book-bound/frontend/src/app/layout.tsx
        {children}
========
        <AuthProvider>
          <Navbar />
          {children}
          </AuthProvider>
>>>>>>>> c7eec8b99a9c4069961b4ceb032059cb2a88b432:notera/src/app/layout.tsx
      </body>
    </html>
  );
}
